/**:
  ros__parameters:
    # Parameters that you want to evaluate
    stddev_vx: 0.2
    coef_vx: 1.0
    angular_velocity_stddev_xx: 0.03
    angular_velocity_stddev_yy: 0.03
    angular_velocity_stddev_zz: 0.03
    angular_velocity_offset_x: 0.0
    angular_velocity_offset_y: 0.0
    angular_velocity_offset_z: 0.0

    # Dead Reckoning configuration
    wait_duration: 6.0 # [s]
    wait_scale: 1.3

    need_ekf_initial_trigger: true
