/**:
  ros__parameters:
    # Parameters that you want to evaluate
    stddev_vx: 0.2 # [m/s]
    coef_vx: 1.0 # [.]

    # Dead Reckoning configuration
    wait_duration: 4.0 # [s]
    wait_scale: 1.3 # [.]

    need_ekf_initial_trigger: true
