/**:
  ros__parameters:
    # Parameters that you want to evaluate
    stddev_vx: 0.3 # [m/s]
    stddev_wz: 0.02 # [rad/s]
    coef_vx: 1.0 # [.]
    bias_wz: 0.0 # [rad/s]

    # Dead Reckoning configuration
    wait_duration: 4.0 # [s]
    wait_scale: 1.3

    need_ekf_initial_trigger: false
